trigger:
- backend-feature

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self  # Checks out the source code of the repository

- script: |
    sudo apt-get update
    sudo apt-get install -y wget
    wget https://dot.net/v1/dotnet-install.sh
    chmod +x dotnet-install.sh
    ./dotnet-install.sh --version 7.0
  displayName: 'Setup .NET 7.0'

- script: dotnet restore ReceptAI.sln
  displayName: 'Restore dependencies'

- script: dotnet build ReceptAI.sln --no-restore -c Release
  displayName: 'Build the solution'

- script: dotnet test ReceptAI.sln --no-build -c Release --verbosity normal
  displayName: 'Run tests'
