name: receptai
description: "ReceptAI"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  dio: ^5.4.3+1
  native_flutter_proxy: ^0.1.15
  mockito: ^5.4.4
  build_runner: ^2.4.9
  test: 1.24.9

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-VariableFont.ttf