name: Feature Branch CI

on:
  push:
    branches:
      - backend-feature

env:
  DOTNET_VERSION: '7.0'
  SOLUTION_NAME: 'ReceptAI.sln'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Cache NuGet packages
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/${{ env.SOLUTION_NAME }}') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_NAME }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_NAME }} --no-restore -c Release

      - name: Run tests
        run: dotnet test ${{ env.SOLUTION_NAME }} --no-build -c Release --verbosity normal
