name: mobile-feature

on:
  push:
    branches:
      - mobile

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'

    - name: Get dependencies
      run: flutter pub get

    - name: Run Flutter build
      run: flutter build apk

    - name: Run tests
      run: flutter test
