name: mobile

on:
  push:
    branches:
      - mobile

env:
  FLUTTER_VERSION: '3.19.6'  # Centralize the Flutter version for easy updates

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          ./.dart_tool
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    - name: Get dependencies
      run: flutter pub get

    - name: Run Flutter build
      run: flutter build apk

    - name: Run tests
      run: flutter test

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: Built APK
        path: build/app/outputs/flutter-apk/app-release.apk
